name: Documentation

# Controls when the workflow will run
on:
  push:
    paths:
      - 'metats/**/*.py'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'metats/**/*.py'
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # installing packages
      - name: Installing dependencies
        run: pip install -r requirements.txt

      # API Reference
      - name: Building API Reference
        run: pdoc metats -o docs/api

      - name: setup git config
        run: |
          git config user.name "Documentation Bot"
          git config user.email "<>"
      
      - name: commit generated docs
        run: |
          git add docs
          git commit -m "updating the API reference"
          git push origin main
